# This is a basic workflow to help you get started with Actions

name: Makepkg

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Makepkg Build and Check
        id: makepkg
        # You may pin to the exact commit or the version.
        # uses: edlanglois/pkgbuild-action@5bb737e69e6a5a171327e6bcf8adace04814685c
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          # Relative path to directory containing the PKGBUILD file.
          pkgdir: .github # optional, default is .
          # Support AUR dependencies if nonempty.
          aurDeps: # optional, default is 
          # Disable namcap checks if nonempty.
          namcapDisable: # optional, default is 
          # A comma-separated list of rules for namcap to run.
          namcapRules: # optional, default is 
          # A comma-separated list of rules for namcap not to run.
          namcapExcludeRules: # optional, default is 
          # Additional arguments to pass to makepkg.
          makepkgArgs: # optional, default is
          
      - name: Print Package Files
        run: |
          echo "Successfully created the following package archive"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
          
      # Uncomment to upload the package as an artifact    
      #- name: Upload Package Archive
        #uses: actions/upload-artifact@v2
        #with:
          #path: ${{ steps.makepkg.outputs.pkgfile0 }}
    
      - id: upload-prepare
        shell: bash -O extglob {0}
        run: |
          echo "## ssh setup"
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          echo "::set-output name=upload-files::./${{ steps.makepkg.outputs.pkgfile0 }}"
    
      - id: upload-github-release
        shell: bash -O extglob {0}
        run: |
          echo "## github upload"
          echo ${{ github.token }} | gh auth login --with-token
          gh release create ${{ steps.makepkg.outputs.pkgfile0 }} --title ${{ steps.makepkg.outputs.pkgfile0 }} --repo ${{ github.repository }} --notes "automated release" || echo "release already exists"
          GITHUB_LINK=https://github.com/${GITHUB_REPOSITORY}/releases/download/${{ steps.makepkg.outputs.pkgfile0 }}
          gh release upload ${{ steps.makepkg.outputs.pkgfile0 }} --repo ${{ github.repository }} --clobber \
            ${{ steps.upload-prepare.outputs.upload-files }}

#      - name: upload-cdn77
#        shell: bash -O extglob {0}
#        run: |
#          # if is not yet supported in composite https://github.com/actions/runner/blob/main/docs/adrs/0549-composite-run-steps.md#if-condition
#          if [ -z "${{ inputs.cdn77-host }}" ] || [ -z "${{ inputs.cdn77-user }}" ] || [ -z "${{ inputs.cdn77-pwd }}" ]; then 
#            echo "## not (all) credentials given for cdn77 upload"
#            exit 0
#          fi
#          
#          echo "## cdn77 upload"
#          
#          ssh-keyscan -t rsa ${{ inputs.cdn77-host }} >> /home/runner/.ssh/known_hosts
#          ## create target dir
#          sshpass -p "${{ inputs.cdn77-pwd }}" rsync -vaP --stats -e ssh ${{ inputs.edition }} \
#            ${{ inputs.cdn77-user }}@${{ inputs.cdn77-host }}:/www/
#          # upload
#          sshpass -p "${{ inputs.cdn77-pwd }}" rsync -vaP \
#            --stats -e ssh ${{ steps.upload-prepare.outputs.upload-files }} \
#            ${{ inputs.cdn77-user }}@${{ inputs.cdn77-host }}:/www/${{ inputs.edition }}/${{ inputs.version }}/
#
